# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_attrCUSUM_inc_TranPrCt_VSI <- function(Ct_Interval_, Cprev_, refv_, pmf_process, leftmost_closed, rightmost_closed) {
    .Call('attrCUSUM_C_attrCUSUM_inc_TranPrCt_VSI', PACKAGE = 'attrCUSUM', Ct_Interval_, Cprev_, refv_, pmf_process, leftmost_closed, rightmost_closed)
}

C_attrCUSUM_inc_Q_VSI <- function(endpoints, refv, pmf_process, leftmost_closed, rightmost_closed) {
    .Call('attrCUSUM_C_attrCUSUM_inc_Q_VSI', PACKAGE = 'attrCUSUM', endpoints, refv, pmf_process, leftmost_closed, rightmost_closed)
}

C_attrCUSUM_getEigen <- function(Q_mat) {
    .Call('attrCUSUM_C_attrCUSUM_getEigen', PACKAGE = 'attrCUSUM', Q_mat)
}

C_attrCUSUM_inc_InitPr_VSI <- function(endpoints, c_zero, refv, pmf_process, leftmost_closed, rightmost_closed) {
    .Call('attrCUSUM_C_attrCUSUM_inc_InitPr_VSI', PACKAGE = 'attrCUSUM', endpoints, c_zero, refv, pmf_process, leftmost_closed, rightmost_closed)
}

C_attrCUSUM_getATA <- function(Q_) {
    .Call('attrCUSUM_C_attrCUSUM_getATA', PACKAGE = 'attrCUSUM', Q_)
}

C_ImportSubseq <- function(x_, ind_b_R_, ind_e_R_) {
    .Call('attrCUSUM_C_ImportSubseq', PACKAGE = 'attrCUSUM', x_, ind_b_R_, ind_e_R_)
}

C_ImportSubseq_Rind <- function(x_, ind_b_R_, ind_e_R_) {
    .Call('attrCUSUM_C_ImportSubseq_Rind', PACKAGE = 'attrCUSUM', x_, ind_b_R_, ind_e_R_)
}

C_ImportSubseq_Cind <- function(x_, ind_b_C_, ind_e_C_) {
    .Call('attrCUSUM_C_ImportSubseq_Cind', PACKAGE = 'attrCUSUM', x_, ind_b_C_, ind_e_C_)
}

C_ndecimal <- function(x_, maxndecimal_) {
    .Call('attrCUSUM_C_ndecimal', PACKAGE = 'attrCUSUM', x_, maxndecimal_)
}

C_indicator_x_in_I <- function(x_, Interval_, leftmost_closed_, rightmost_closed_, ndec_) {
    .Call('attrCUSUM_C_indicator_x_in_I', PACKAGE = 'attrCUSUM', x_, Interval_, leftmost_closed_, rightmost_closed_, ndec_)
}

